version: "3.8"

services:
  nave_db:
    image: postgres
    container_name: navedex
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - nave-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  nave-data:
